version: v2
plugins:
  - remote: buf.build/grpc-ecosystem/openapiv2
    out: docs/openapi
    opt:
      - json_names_for_fields=true
      - include_package_in_tags=true
      - openapi_naming_strategy=fqn
      - generate_unbound_methods=true
